- .idea/workspace.xml
- bbs.css
- client/find.html
- client/find.js
- client/post.html
- client/post.js
- server/server.js
> Added likes and dislikes.

- .idea/workspace.xml
- server/server.js
If wallet doesn't exist then it creates a new one and sets karma to 1.
> Liked posts' posters gain karma when post is liked.

- .idea/workspace.xml
- client/profile.html
- client/profile.js
- server/server.js
Fixed karma so it gets incremented by 1 or initialized to 1 if it doesn't exist on like.
> Fixed bug allowing poster to like or dislike his own post.

- .idea/workspace.xml
- bbs.css
- client/find.html
- client/find.js
- client/post.html
- client/post.js
- lib/game/duckpunches.js
- lib/router.js
- server/server.js
> Abbreviated messages found by search.html in find.html

- .idea/workspace.xml
- bbs.css
- client/home.js
- client/post.js
- lib/utilities.js
- server/server.js
Added bbcode italic, bold, and underline.
> Fixed urlify returning no post if url isn't found.

- client/game.html
- client/game.js
- client/global/helpers.js
- lib/game/combat.js
- lib/game/data.js
- lib/game/duckpunches.js
- lib/game/unit.js
- lib/utilities.js
- server/game.js
-Battles go until one side dies.
-When all players die, get kicked back to town
-When all enemies die, get another batch of em to kill!
> Core of combat now works 100%!

- .idea/workspace.xml
- client/find.html
- client/find.js
fixed a few bugs in highlighting found text in find.html
> Added quote bbcode to displayed found posts in find.html

- .idea/workspace.xml
- client/header.html
- client/header.js
- client/home.html
- client/thread.html
- lib/router.js
Fixed breadcrumbs for game and unit page.
Renamed game to Ryuusei RPG
> Attempting to fix the size of the board for mobile devices.

- .idea/workspace.xml
- bbs.css
- client/header.html
- client/pmPage.html
- client/post.html
- client/thread.html
This might make everything seem bigger for pc users.
Oh well. We'll see.
> Trying to fix the size of text for a mobile device.

- .idea/workspace.xml
- bbs.css
- client/game/unit.html
- client/game/unit.js
- client/global/helpers.js
Resized font sizes in bbs.css to fit the board better.
> Fixed stats not showing up on game/unit.html.

- .idea/workspace.xml
- bbs.css
- client/client.js
- client/controlpanel.html
- client/editTopic.html
- client/find.html
- client/footer.html
- client/game.html
- client/header.html
- client/home.html
- client/inbox.html
- client/notFound.html
- client/pmPage.html
- client/post.html
- client/profile.html
- client/search.html
- client/subs.html
- client/thread.html
- client/users.html
Reformatted the subscriptions new posts button to fit the wallet div.
> Took off all the container divs because it wastes space on the pages.

- .idea/workspace.xml
- bbs.css
- client/game/game.js
- client/game/shop.html
- client/game/shop.js
- client/global/helpers.js
However, they don't move around depending on how close the mouse is to the edge of the screen yet
> Got tooltip suggestions working.

- lib/game/duckpunches.js
- server/game.js
adds the beginnings of unit recruitment
> Hopefully fixes issues with stat-tracking timer and general shit

- client/BBS/controlpanel.html
- client/BBS/controlpanel.js
- lib/game/duckpunches.js
- server/game.js
styles admin buttons on controlpanel.html
> Adds a 'purge combat' and 'purge game' button to the controlpanel

- client/game/game.html
- client/game/game.js
- client/game/shop.js
- client/game/summary.html
- lib/game/util.js
- server/game.js
- server/lootGeneration.js
> Adds basic loot generation (testing)

- .idea/workspace.xml
- bbs.css
- client/game/inventory.html
- client/game/inventory.js
- client/game/shop.html
- client/game/shop.js
- client/global/helpers.js
- lib/game/data/items.js
- lib/router.js
- server/game.js
- server/lootGeneration.js
Added ability to buy items in shop.html
> Added tooltips to inventory.html

- .idea/workspace.xml
- client/game/shop.html
- client/game/shop.js
- client/game/tooltipsWithSuggestion.html
- client/game/tooltipsWithSuggestion.js
- client/game/unit.html
- client/game/unit.js
Made tooltipsWithSuggestions template to easily add tooltips to a page
> Fixed tooltips in unit.html

- .idea/workspace.xml
- bbs.css
- client/game/pages/equipunit.html
- client/game/pages/equipunit.js
Added tooltips for the equipped items in equipunit.html
> Fixed formatting of tooltips on equipunit.html

- server/game.js
problem was with combat ending on 'cheat' frames
> Fixes server going rip

- .idea/workspace.xml
- client/client.js
- client/game/pages/shop.js
- client/game/templates/tooltipsWithSuggestion.html
- client/game/templates/tooltipsWithSuggestion.js
fixed greatswords not showing equip tooltips in tooltipsWithSuggestion.html
> added resistances to tooltipsWithSuggestion.html
